### PR TITLE
Update SerenityObjectFactory to use the new cucumber 4.8 mode, added…

### PR DESCRIPTION
**Pull request by ricardorlg-aval**
… cucumber.properties to refer to it.

### CODE REVIEW

**Comment by wakaleo** [comment]
Integrated manually

**Comment by wakaleo** [comment]
The new ObjectFactory doesn't seem to get picked up correctly, so reverting pending further research.

**Comment by ricardorlg-aval** [comment]
Yes u need to setup the factory using the cucumber properties, the Pull Request do that,

**Comment by ricardorlg-aval** [comment]
@wakaleo If u add the cucumber.properties file to main resources with cucumber.object-factory=cucumber.runtime.SerenityObjectFactory it should work.

**Comment by wakaleo** [comment]
No, I tried that and it doesn’t work. Liviu checked with the Cucumber devs and it appears we will need to wait until Cucumber 5 for this to work .

**Comment by ricardorlg-aval** [comment]
Mmm that's weird I use it as local in my project and it works, and in the PR the tests passes. Really weird I will check again.

**Comment by cliviu** [comment]
@ricardorlg-aval I'm not sure what happens if we include a "cucumber.properties" in Serenity ... What happens then with the user specific  "cucumber.properties" ?

**Comment by ricardorlg-aval** [comment]
I think it will not impact serenity, cause we are just definning the property for ObjectFactory so cucumber will use Serenity one instead of the default, user specific options will be added, the only problem I think could be if an specific user configuration overrides the object factory but that its ouside of our control. I use a local version of serenity cucumber with this configuration and in my projects and tests everithing works, I will review it again today and maybe we can just make a candidate and see if some serenity users can test it to get some feedback.

**Comment by cliviu** [comment]
hi @ricardorlg-aval , this is exactly my problem  "specific user configuration overrides the object factory" - If a user has  a "cucumber.properties" in the application project , the "cucumber.properties" from the Serenity will be overwritten. At the end of the day there will be only one "cucumber.properties" file loaded.

**Comment by ricardorlg-aval** [comment]
mmm the other option is to use service loader instead of properties, add a service entry in META-INF/services to point to serenity ObjectFactory.

**Pull request closed without merging**
